version: '3.5'
services:
  auth-service:
    image: food-service
    depends_on:
      - postgres
    ports:
      - 8081:8081
    network_mode: "host"
    build:
         context: ./auth-service
         dockerfile: ./Dockerfile
         args:
           JAR_FILE: './auth-service-0.1.0.jar'
  food-service:
    image: auth-service
    depends_on:
      - postgres
    ports:
      - 8080:8080
    network_mode: "host"
    build:
      context: ./food-service
      dockerfile: ./Dockerfile
      args:
        JAR_FILE: './food-service-0.1.0.jar'
  postgres:
      image: postgres
      restart: always
      ports:
        - 5433:5432
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: food