server:
    port: 8080
spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/food
        username: postgres
        password: postgres
    jpa:
         show-sql: true
         generate-ddl: true
         database: POSTGRESQL
         database-platform: org.hibernate.dialect.PostgreSQLDialect

         properties:
           hibernate:
              ddl-auto: update
              temp:
                    use_jdbc_metadata_defaults: false
           jdbc:
              lob:
                non_contextual_creation: true
security:
  oauth2:
    client:
      client-id: food-delivery
      client-secret: food-delivery-secret
      scope: read,write
      auto-approve-scopes: '.*'
      access-token-uri: http://localhost:8081/oauth/token
    resource:
      user-info-uri: http://localhost:8081/me

